# Generated by Django 2.2.5 on 2019-09-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Name',
            new_name='name',
        ),
    ]
