# Generated by Django 2.2.5 on 2019-09-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190923_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.TextField(default='', max_length=40),
        ),
    ]
