# Generated by Django 2.2.5 on 2019-09-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190923_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
