# Generated by Django 2.2.5 on 2019-09-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190923_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
