# Generated by Django 2.1.7 on 2019-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
