# Generated by Django 2.1.7 on 2019-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_short_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_summary',
            field=models.TextField(),
        ),
    ]
